# made by @PapichX


from time import sleep
from userbot.events import register


@register(outgoing=True, pattern='^.mn(?: |$)(.*)')
async def typewriter(typew):
    await typew.edit("🌚")
    sleep(0.10)
    await typew.edit("🌝")
    sleep(0.10)
    await typew.edit("🌚")
    sleep(0.10)
    await typew.edit("🌝")
    sleep(0.10)
    await typew.edit("🌚")
    sleep(0.10)
    await typew.edit("🌝")
    sleep(0.10)
    await typew.edit("🌚")
    sleep(0.10)
    await typew.edit("🌝")
    sleep(0.10)
    await typew.edit("🌚")
    sleep(0.10)
    await typew.edit("🌝")
    sleep(0.10)
    await typew.edit("🌚")
    sleep(0.10)
    await typew.edit("🌝")
    sleep(0.10)
    await typew.edit("🌚")
    sleep(0.10)
    await typew.edit("🌝")
    sleep(0.10)
    await typew.edit("🌚")
    sleep(0.10)
    await typew.edit("🌝")
    sleep(0.10)
    await typew.edit("🌚")
    sleep(0.10)
    await typew.edit("🌝")
    sleep(0.10)
    await typew.edit("🌚")
    sleep(0.10)
    await typew.edit("🌝")
    sleep(0.10)
    await typew.edit("🌚")
    sleep(0.10)
    await typew.edit("🌝")

