# made by @PapichX


from time import sleep
from userbot.events import register


@register(outgoing=True, pattern='^.ff(?: |$)(.*)')
async def typewriter(typew):
    await typew.edit("Ты чмо")
    sleep(0.30)
    await typew.edit("Гандон")
    sleep(0.30)
    await typew.edit("уебок")
    sleep(0.30)
    await typew.edit("пидарас")
    sleep(0.30)
    await typew.edit("бомж")
    sleep(0.30)
    await typew.edit("бот")
    sleep(0.30)
    await typew.edit("слит")
    sleep(0.30)
    await typew.edit("гавноед")
    sleep(0.30)
    await typew.edit("пидораСина")
    sleep(0.30)
    await typew.edit("Хуесос")
    sleep(0.30)
    await typew.edit("Блядина")
    sleep(0.30)
    await typew.edit("МММ ДАУН")
    sleep(0.30)
    await typew.edit("всосар")
    sleep(0.30)
    await typew.edit("и мать сосет")
    sleep(0.30)
    await typew.edit("в канаве мамаша")
    sleep(0.30)
    await typew.edit("ой фу")
    sleep(0.30)
    await typew.edit("чикибамбони")
    sleep(0.30)
    await typew.edit("пиздабол")
    sleep(0.30)
    await typew.edit("пердеж")
    sleep(0.30)
    await typew.edit("говно")
    sleep(0.30)
    await typew.edit("животное")
    sleep(0.30)
    await typew.edit("уебок")
    sleep(0.30)
    await typew.edit("хуй пососер")
    sleep(0.30)
    await typew.edit("мать жива?")
    sleep(0.30)
    await typew.edit("хуй пососер")
    sleep(0.30)
    await typew.edit("и вообще")
    sleep(0.30)
    await typew.edit("иди нахуй")
    sleep(0.30)
    await typew.edit("ПЕТУШАРА")
    

